<div class="categorygroup">
<div class="category">
<h3 class="categorytitle">Get QuantLib</h3>
<p class=categorysummary>Head to our <a
href="/download.shtml">download</a> page to get the latest official
release, or check out the latest development version from our <a
href="/git.shtml">git</a> repository.
QuantLib is also available in <a href="/extensions.shtml">other
languages</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">Documentation</h3>
<p class=categorysummary><a href="/docs.shtml">Documentation is
available</a> in several formats from a number of sources. You can
also read our <a href="/install.shtml">Installation instructions</a>
to get QuantLib working on your computer.</p>
</div>

<div class="category">
<h3 class="categorytitle">Need Help?</h3>
<p class=categorysummary>If you need to ask a question, subscribe to
our <a href="/mailinglists.shtml">mailing list</a> and post it
there. Before doing that, though, you might want to look at the <a
href="/faq.shtml">FAQ</a> and check if it was already answered.</p>
</div>
</div>

<div class="categorygroup">
<div class="category">
<h3 class="categorytitle">Found a bug?</h3>
<p class=categorysummary>If you have a patch, open a pull request on <a href="https://github.com/lballabio/quantlib/pulls">GitHub</a> or post it to our <a href=
"http://sourceforge.net/tracker/?group_id=12740&amp;atid=312740">patch manager</a>.  Otherwise, report the bug on our <a href=
"http://sourceforge.net/tracker/?func=add&amp;group_id=12740&amp;atid=112740">issue tracker</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">Want to contribute?</h3>
<p class=categorysummary>Just fork our repository on <a
href="https://github.com/lballabio/quantlib">GitHub</a> and start
coding (instructions are <a
href="https://help.github.com/articles/fork-a-repo">here</a>).  Please
have a look at our <a href="/newdeveloper.shtml">developer intro</a>
and <a href="/style.shtml">guidelines</a>.</p>
</div>

<div class="category">
<h3 class="categorytitle">More info</h3>
<p class=categorysummary>Here is the QuantLib <a
href="/license.shtml">license</a>, the <a
href="/reference/group.html">list of contributors</a>, and the <a
href="/reference/history.html">version history</a>. The project page
on Sourceforge is available at <a
href="http://sourceforge.net/projects/quantlib">this link</a>.</p>
</div>
</div>

